name: Deploy Backend Services

on:
  push:
    paths:
      - 'server/**' # Trigger workflow when changes are made in the `server/` folder.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js for TypeScript compilation
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # Step 3: Install dependencies and compile TypeScript for each service
    - name: Install Dependencies & Build Services
      run: |
        for service in auth-service user-service product-service inventory-service payment-service review-service order-service cart-service
        do
          echo "Building $service..."
          npm install --prefix server/$service
          npm run build --prefix server/$service
        done

    # Step 4: Deploy the compiled JavaScript code to EC2
    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_PUBLIC_IP }}
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 400 key.pem

        # Dynamically create the deployment script
        echo "#!/bin/bash
        cd /home/ec2-user/\$1
        pm2 restart \$1 || pm2 start dist/server.js --name \$1
        " > deploy_service.sh

        # Make the script executable
        chmod +x deploy_service.sh

        # Deploy each service
        for service in auth-service user-service product-service inventory-service payment-service review-service order-service cart-service
        do
          echo "Deploying $service..."

          # Copy the compiled files to the service directory
          scp -i key.pem -o StrictHostKeyChecking=no -r server/$service/dist ec2-user@${EC2_HOST}:$service
          echo "Copied dist files for $service."

          # Copy the deployment script to the EC2 instance
          scp -i key.pem -o StrictHostKeyChecking=no deploy_service.sh ec2-user@${EC2_HOST}:
          echo "Copied deployment script to EC2."

          # Execute the deployment script for the service
          ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@${EC2_HOST} "bash ~/deploy_service.sh $service"
          echo "Executed deployment script for $service."
        done

